MovieCRUD/Models/ErrorViewModel.cs
namespace MovieCRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieCRUD/Models/Genre.cs
namespace MovieCRUD.Models
{
    public class Genre
    {
        public string GenreId { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;

    }
}

MovieCRUD/Models/Movie.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace MovieCRUD.Models
{
    public class Movie
    {
        // EF Core will configure the database to generate this value
        public int MovieId { get; set; }

        [Required(ErrorMessage = "Please enter a name.")]
        public string Name { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a year.")]
        [Range(1889, 2999, ErrorMessage = "Year must be after 1889.")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "Please enter a rating.")]
        [Range(1, 5, ErrorMessage =
            "Rating must be between 1 and 5.")]
        public int? Rating { get; set; }

        [Required(ErrorMessage = "Please enter a genre.")]
        public string GenreId { get; set; } = string.Empty;

        [ValidateNever]
        public Genre Genre { get; set; } = null!;

        public string Slug =>
           Name?.Replace(' ', '-').ToLower() + '-' + Year?.ToString();

    }
}

MovieCRUD/Models/MovieContext.cs
using Microsoft.EntityFrameworkCore;

namespace MovieCRUD.Models
{
        public class MovieContext : DbContext
        {
            public MovieContext(DbContextOptions<MovieContext> options)
                : base(options)
            { }

            public DbSet<Movie> Movies { get; set; } = null!;
            public DbSet<Genre> Genres { get; set; } = null!;


            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                 modelBuilder.Entity<Genre>().HasData(
                 new Genre { GenreId = "A", Name = "Action" },
                 new Genre { GenreId = "C", Name = "Comedy" },
                 new Genre { GenreId = "D", Name = "Drama" },
                 new Genre { GenreId = "H", Name = "Horror" },
                 new Genre { GenreId = "M", Name = "Musical" },
                 new Genre { GenreId = "R", Name = "RomCom" },
                 new Genre { GenreId = "S", Name = "SciFi" }
                 );

                 modelBuilder.Entity<Movie>().HasData(
                   new Movie
                   {
                       MovieId = 1,
                       Name = "Casablanca",
                       Year = 1942,
                       Rating = 5,
                       GenreId = "D"
                   },
                   new Movie
                   {
                       MovieId = 2,
                       Name = "Wonder Woman",
                       Year = 2017,
                       Rating = 3,
                       GenreId = "A"
                   },
                   new Movie
                   {
                       MovieId = 3,
                       Name = "Moonstruck",
                       Year = 1988,
                       Rating = 4,
                       GenreId = "R"
                   }
                   );
            }
        }
}

MovieCRUD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieCRUD.Models;
using System.Diagnostics;

namespace MovieCRUD.Controllers
{
    public class HomeController : Controller
    {
        private MovieContext context { get; set; }

        public HomeController(MovieContext ctx) => context = ctx;

        public IActionResult Index()
        {
            var movies = context.Movies
                .Include(m => m.Genre)
                .OrderBy(m => m.Name)
                .ToList();

            return View(movies);
        }
    }
}

MovieCRUD/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieCRUD.Models;

namespace MovieCRUD.Controllers
{
    public class MovieController : Controller
    {
        private MovieContext context { get; set; }

        public MovieController(MovieContext ctx) => context = ctx;

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
            return View("Edit", new Movie());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
            var movie = context.Movies.Find(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            if (ModelState.IsValid)
            {
                if (movie.MovieId == 0)
                    context.Movies.Add(movie);
                else
                    context.Movies.Update(movie);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (movie.MovieId == 0) ? "Add" : "Edit";
                ViewBag.Genres = context.Genres.OrderBy(g => g.Name).ToList();
                return View(movie);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var movie = context.Movies.Find(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Delete(Movie movie)
        {
            context.Movies.Remove(movie);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

MovieCRUD/Views/Home/Index.cshtml
@model List<Movie>
@{
    ViewData["Title"] = "My Movies";
}
<div class="mb-2  head">
    <a asp-controller="Movie" asp-action="Add">Add New Movie</a>
    
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Year</th>
            <th>Genre</th>
            <th>Rating</th><th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var movie in Model)
        {
                <tr>
                    <td>@movie.Name</td>
                    <td>@movie.Year</td>
                    <td>@movie.Genre.Name</td>
                    <td>@movie.Rating</td>
                    <td>
                        <a asp-controller="Movie" asp-action="Edit"
                       asp-route-id="@movie.MovieId"
                       asp-route-slug="@movie.Slug">Edit</a>
                        <a asp-controller="Movie" asp-action="Delete"
                       asp-route-id="@movie.MovieId"
                       asp-route-slug="@movie.Slug">Delete</a>
                    </td>
                </tr>
        }
    </tbody>
</table>

MovieCRUD/Views/Movie/Create.cshtml
@model MovieCRUD.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieCRUD/Views/Movie/Delete.cshtml
@model MovieCRUD.Models.Movie

@{
    ViewData["Title"] = "Delete Movie";
}

<h2>Confirm Deletion</h2>
<h3>@Model.Name (@Model.Year)</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="MovieId" />

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

MovieCRUD/Views/Movie/Details.cshtml
@model MovieCRUD.Models.Movie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MovieId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MovieCRUD/Views/Movie/Edit.cshtml
@model MovieCRUD.Models.Movie
@{
    string title = ViewBag.Action + " Movie";
    ViewData["Title"] = title;
}
 
<h2>@ViewBag.Title</h2>
 
<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Year" class="form-label">Year</label>
        <input asp-for="Year" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="GenreId" class="form-label">Genre</label>
        <select asp-for="GenreId" class="form-select">
            <option value="">select a genre</option> 
            @foreach (Genre g in ViewBag.Genres)
            {
                    <option value="@g.GenreId">@g.Name</option>
            }
        </select>
    </div>

    <div class="mb-3">
        <label asp-for="Rating" class="form-label">Rating</label>
        <input asp-for="Rating" class="form-control">
    </div>

    <input type="hidden" asp-for="MovieId" />

    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

MovieCRUD/Views/Movie/Index.cshtml
@model IEnumerable<MovieCRUD.Models.Movie>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MovieId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MovieId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MovieId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MovieCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel=" stylesheet" href="../wwwroot/css/site.css" />
</head>
<body>
    <div class="container">
        <header class="p-4 mb-3 bg-secondary border">
            <h1 class="text-center text-white">My Movies</h1>
        </header>
        @RenderBody()
    </div>
</body>
</html>